---
title: "Variations on state-level plots"
author: "Jake Hofman (jhofman)"
date: '`r Sys.time()`'
output:
  html_document:
    code_folding: hide
    number_sections: yes
    toc: yes
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-libraries}
library(tidyverse)
library(scales)
library(plotly)
library(gganimate)

source('covid_log_log_diff/functions.R')
```

```{r prep-data-frames}
covidByState <- loadAndFormatNytimesCovidPerState()

covidByState<-covidByState %>% 
  dplyr::filter(!is.na(newCasesPerDay), 
                !is.na(cases), 
                newCasesPerDay > 0, 
                cases > 0)  %>%
  dplyr::select(-fips,-prevDate,-prevCases)

snippet<-covidByState %>% group_by(date) %>% 
  summarize(
    state = "USA",
    cases = sum(cases),
    deaths=sum(deaths),
    newCasesPerDay = sum(newCasesPerDay)
  )

covidByState = bind_rows(snippet, covidByState)

# create loess-smoothed versions of time series for each state
covidByStateSmoothed <- covidByState %>%
  filter(!(state %in% c("USA","Northern Mariana Islands","Virgin Islands","Guam"))) %>%
  group_by(state) %>%
  do(data.frame(.,
                smoothed = 10^predict(loess(log10(newCasesPerDay) ~ log10(cases), data = .), .))) %>%
  ungroup()
```

# Single state, highlighted with background
```{r single-state-highlighted}
covidByStateSmoothed %>%
  filter(state == "New York") %>%
  ggplot(aes(x=cases, y=smoothed)) +
  geom_line(data = covidByStateSmoothed, aes(group = state), color = "grey") +
  geom_line(aes(y = smoothed), color = "red") +
  scale_x_log10(label = comma) + 
  scale_y_log10(label = comma) +
  coord_equal() +
  theme_minimal() +
  labs(x = 'Total confirmed cases',
       y = 'New confirmed cases per day',
       title = 'Trajectory of COVID-19 cases for New York State',
       subtitle = 'Grey lines show other U.S. states')
```

## Interactive

```{r single-state-highlighted-interactivce}

#d <- highlight_key(covidByStateSmoothed, ~state)

selected_state <- "New York"

background_states <- c("New York", "New Jersey", "California", "Michigan", "Louisiana", "Florida", "Massachusetts", "Illinois", "Pennsylvania", "Washington")
background_states <- setdiff(background_states, selected_state)

plot_data <- covidByStateSmoothed %>%
  filter(state %in% background_states) %>%
  ungroup() %>%
  arrange(state, date) %>%
  mutate(state = as.factor(state),
         state = reorder(state, -newCasesPerDay, last))
  
d <- plot_data %>%
  highlight_key(~state)

covidByStateSmoothMostRecent <- plot_data %>%
  group_by(state) %>%
  arrange(desc(date)) %>%
  slice(1) %>%
  ungroup()

# ggplot will complain about ignoring an unknown aesthetic
# this is a side effect of a hack to get tooltips to show up in plotly
# so supress warnings and then turn them back on after the ggplot calls
options(warn = -1)

p <- covidByStateSmoothed %>%
  filter(state == selected_state) %>%
  ggplot(aes(x=cases, y=smoothed)) +
  #geom_line(data = d, aes(group = state, text = sprintf('%s on %s:\n%s total cases\n%s new cases', state, date, comma(cases), comma(newCasesPerDay))), color = "grey") +
  geom_point(data = d, aes(group = state, color = state, text = sprintf('%s on %s:\n%s total cases\n%s new cases', state, date, comma(cases), comma(newCasesPerDay))), size = 0.3, alpha = 1) +
  geom_line(data = d, aes(group = state, color = state, text = sprintf('%s on %s:\n%s total cases\n%s new cases', state, date, comma(cases), comma(newCasesPerDay))), alpha = 0.5) +
  #geom_point(data = covidByStateSmoothMostRecent, aes(x = cases, y = smoothed, group = state), size = 2, color = "grey", alpha = 0.5) +
  geom_point(data = covidByStateSmoothMostRecent, aes(x = cases, y = smoothed, group = state, color = state), size = 2, alpha = 0.5) +
  #geom_point(data = d, aes(x = last(cases), y = last(smoothed), text = sprintf('Foo')), size = 2, color = "red", alpha = 0.5) +
  geom_line(aes(y = smoothed), color = "black") +
  geom_point(aes(x = last(cases), y = last(smoothed)), size = 2, color = "black", alpha = 0.5) +
  geom_text(aes(x = last(cases), y = 1.2*last(smoothed), label = state)) +
  geom_point(aes(y = smoothed, text = sprintf('%s on %s:\n%s total cases\n%s new cases', state, date, comma(cases), comma(newCasesPerDay))), size = 0.3, alpha = 1) +
  scale_x_log10(label = comma) + 
  scale_y_log10(label = comma) +
  coord_equal() +
  theme_minimal() +
  labs(x = 'Total confirmed cases',
       y = 'New confirmed cases per day',
       title = 'Trajectory of COVID-19 cases for New York State',
       subtitle = 'Grey lines show other U.S. states')

  #scale_color_brewer(type = "qualitative", palette = "Pastel1")

# back to regular warning levels
options(warn = 0)

fig <- ggplotly(p, tooltip = "text") #%>%
  #highlight(on = "plotly_hover", off = "plotly_deselect", color = "black" )

fig
```

# All states, faceted
```{r all-states-faceted, fig.width=8, fig.height = 8}
ggplot(covidByStateSmoothed, aes(x=cases, y=smoothed, group = state)) +
  geom_line(data = covidByStateSmoothed %>% rename(group = state),
            aes(x = cases, y = smoothed, group = group), color = "grey") +
  geom_line(aes(y = smoothed), color = "red") +
  scale_x_log10(label = comma, breaks = c(100, 1000, 100000)) + 
  scale_y_log10(label = comma) +
  coord_equal() +
  labs(x = 'Total confirmed cases',
       y = 'New confirmed cases per day',
       title = 'Trajectory of COVID-19 cases in the U.S.') +
  facet_wrap(~ state) +
  theme_minimal()
```



# Single state, highlighted with background, animated
```{r single-state-highlighted-animated}
covidByStateSmoothed %>%
  filter(state == "New York") %>%
  ggplot(aes(x=cases, y=smoothed)) +
  geom_line(data = covidByStateSmoothed, aes(group = state), color = "grey") +
  geom_line(aes(y = smoothed), color = "red") +
  geom_label(aes(label = state)) +
  geom_text(aes(x = 3e4, y = 1.5, label = date)) +
  scale_x_log10(label = comma) + 
  scale_y_log10(label = comma) +
  coord_equal() +
  theme_minimal() +
  transition_reveal(date) +
  labs(x = 'Total confirmed cases',
       y = 'New confirmed cases per day',
       title = 'Trajectory of COVID-19 cases for New York State',
       subtitle = 'Grey lines show other U.S. states')
```

# All states, animated
```{r all-states-animated}
covidByStateSmoothed %>%
  filter(state != "USA") %>%
  ggplot(aes(x=cases, y=smoothed, group = state)) +
  geom_text(aes(label = state)) +
  geom_text(aes(x = 3e4, y = 1.5, label = date)) +
  geom_line(aes(y = smoothed)) +
  scale_x_log10(label = comma) + 
  scale_y_log10(label = comma) +
  coord_equal() +
  transition_reveal(date) +
  theme_minimal() +
  labs(x = 'Total confirmed cases',
       y = 'New confirmed cases per day',
       title = 'Trajectory of COVID-19 cases in the U.S.')
```
